import type { Metadata } from "next";
import { Geist, Geist_Mono, Figtree } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";
import { cn } from "@/lib/utils";
import { ThemeProvider } from "@/components/ThemeProvider";
import PortfolioSidebarMenu from "@/components/PortfolioSidebarMenu";
import { ModeToggle } from "@/components/ModeToggle";
import LangToggle from "@/components/LangToggle";
import { LanguageProvider } from "@/components/LanguageProvider";
import MobileBottomNav from "@/components/MobileBottomNav";
import { Code2 } from "lucide-react";

// const figtree = Figtree({ subsets: ["latin"], variable: "--font-sans" });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
export const iranSans = localFont({
  src: "../public/fonts/IRANSansWeb.ttf",
  variable: "--font-iran-sans",
  display: "swap",
});
export const lalezar = localFont({
  src: "../public/fonts/Lalezar-Regular.ttf",
  variable: "--font-lalezar",
  display: "swap",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="fa"
      suppressHydrationWarning
      className={cn(
        "h-full",
        "antialiased",
        geistSans.variable,
        geistMono.variable,
        iranSans.variable,
        lalezar.variable,
      )}
    >
      <body className="min-h-full flex flex-col ">
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <LanguageProvider>
            <div className="w-full flex flex-col md:flex-row items-start  md:p-3 bg-background">
              <PortfolioSidebarMenu />
              <MobileBottomNav />

              <div className="w-full mb-20 md:mb-0  h-auto px-6 py-4 flex flex-col gap-5 ">
                <header className="w-full h-12   flex flex-row-reverse items-center justify-between ">
                  <div className="w-auto h-full flex gap-2 items-center">
                    <ModeToggle />
                    <LangToggle />
                  </div>
                  {/*Logo */}
                  <div className="flex gap-3 items-center md:hidden ">
                    <Code2 className="size-6 shrink-0 text-amber-400" />

                    <p className="whitespace-nowrap font-mono text-amber-400 group-data-[collapsible=icon]:hidden">
                      Maryam Salimi
                    </p>
                  </div>
                </header>
                {children}
              </div>
            </div>
          </LanguageProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
